"""Persistence repository layer re-exporting Supabase database operations."""
from database.supabase_client import (
    save_defect_report,
    save_multi_defect_report,
    validate_defect_item_payload,
    get_defect_reports,
    get_defect_report_by_id,
    get_defect_report_items,
    get_reports_by_employee,
    get_reports_by_category,
    is_supabase_configured,
    check_database_readiness,
    DatabaseError,
    MultiDefectPersistenceError,
    validate_profile_payload,
    get_profile,
    create_profile,
    update_profile,
    get_or_create_profile,
)

__all__ = [
    "save_defect_report",
    "save_multi_defect_report",
    "validate_defect_item_payload",
    "get_defect_reports",
    "get_defect_report_by_id",
    "get_defect_report_items",
    "get_reports_by_employee",
    "get_reports_by_category",
    "is_supabase_configured",
    "check_database_readiness",
    "DatabaseError",
    "MultiDefectPersistenceError",
    "validate_profile_payload",
    "get_profile",
    "create_profile",
    "update_profile",
    "get_or_create_profile",
]
